name: calculator_app_test

on: push

jobs:
 tests:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: subisito/flutter-action@v1.3.0
    - name: install dependencies
      run: flutter packages geet
    - name: run tests
      run: flutter test --exclude-tags='no-ci'
